// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace AnimationFlatbuffer
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public enum PrimitiveFB : byte
{
  NONE = 0,
  LineFB = 1,
  TriangleFB = 2,
  RoundRectFB = 3,
  RotatedRectFB = 4,
  CircleFB = 5,
};



static public class PrimitiveFBVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((PrimitiveFB)typeId)
    {
      case PrimitiveFB.LineFB:
        result = verifier.VerifyUnionData(tablePos, 10, 2);
        break;
      case PrimitiveFB.TriangleFB:
        result = verifier.VerifyUnionData(tablePos, 14, 2);
        break;
      case PrimitiveFB.RoundRectFB:
        result = verifier.VerifyUnionData(tablePos, 12, 2);
        break;
      case PrimitiveFB.RotatedRectFB:
        result = verifier.VerifyUnionData(tablePos, 12, 2);
        break;
      case PrimitiveFB.CircleFB:
        result = verifier.VerifyUnionData(tablePos, 12, 2);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}

public struct LineFB : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public LineFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public short X0 { get { return __p.bb.GetShort(__p.bb_pos + 0); } }
  public short Y0 { get { return __p.bb.GetShort(__p.bb_pos + 2); } }
  public short X1 { get { return __p.bb.GetShort(__p.bb_pos + 4); } }
  public short Y1 { get { return __p.bb.GetShort(__p.bb_pos + 6); } }
  public ushort Color { get { return __p.bb.GetUshort(__p.bb_pos + 8); } }

  public static Offset<AnimationFlatbuffer.LineFB> CreateLineFB(FlatBufferBuilder builder, short X0, short Y0, short X1, short Y1, ushort Color) {
    builder.Prep(2, 10);
    builder.PutUshort(Color);
    builder.PutShort(Y1);
    builder.PutShort(X1);
    builder.PutShort(Y0);
    builder.PutShort(X0);
    return new Offset<AnimationFlatbuffer.LineFB>(builder.Offset);
  }
}

public struct TriangleFB : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public TriangleFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public short X0 { get { return __p.bb.GetShort(__p.bb_pos + 0); } }
  public short Y0 { get { return __p.bb.GetShort(__p.bb_pos + 2); } }
  public short X1 { get { return __p.bb.GetShort(__p.bb_pos + 4); } }
  public short Y1 { get { return __p.bb.GetShort(__p.bb_pos + 6); } }
  public short X2 { get { return __p.bb.GetShort(__p.bb_pos + 8); } }
  public short Y2 { get { return __p.bb.GetShort(__p.bb_pos + 10); } }
  public ushort Color { get { return __p.bb.GetUshort(__p.bb_pos + 12); } }

  public static Offset<AnimationFlatbuffer.TriangleFB> CreateTriangleFB(FlatBufferBuilder builder, short X0, short Y0, short X1, short Y1, short X2, short Y2, ushort Color) {
    builder.Prep(2, 14);
    builder.PutUshort(Color);
    builder.PutShort(Y2);
    builder.PutShort(X2);
    builder.PutShort(Y1);
    builder.PutShort(X1);
    builder.PutShort(Y0);
    builder.PutShort(X0);
    return new Offset<AnimationFlatbuffer.TriangleFB>(builder.Offset);
  }
}

public struct RoundRectFB : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public RoundRectFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public short X0 { get { return __p.bb.GetShort(__p.bb_pos + 0); } }
  public short Y0 { get { return __p.bb.GetShort(__p.bb_pos + 2); } }
  public short W { get { return __p.bb.GetShort(__p.bb_pos + 4); } }
  public short H { get { return __p.bb.GetShort(__p.bb_pos + 6); } }
  public short Radius { get { return __p.bb.GetShort(__p.bb_pos + 8); } }
  public ushort Color { get { return __p.bb.GetUshort(__p.bb_pos + 10); } }

  public static Offset<AnimationFlatbuffer.RoundRectFB> CreateRoundRectFB(FlatBufferBuilder builder, short X0, short Y0, short W, short H, short Radius, ushort Color) {
    builder.Prep(2, 12);
    builder.PutUshort(Color);
    builder.PutShort(Radius);
    builder.PutShort(H);
    builder.PutShort(W);
    builder.PutShort(Y0);
    builder.PutShort(X0);
    return new Offset<AnimationFlatbuffer.RoundRectFB>(builder.Offset);
  }
}

public struct RotatedRectFB : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public RotatedRectFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public short CenX { get { return __p.bb.GetShort(__p.bb_pos + 0); } }
  public short CenY { get { return __p.bb.GetShort(__p.bb_pos + 2); } }
  public short W { get { return __p.bb.GetShort(__p.bb_pos + 4); } }
  public short H { get { return __p.bb.GetShort(__p.bb_pos + 6); } }
  public short AngleDeg { get { return __p.bb.GetShort(__p.bb_pos + 8); } }
  public ushort Color { get { return __p.bb.GetUshort(__p.bb_pos + 10); } }

  public static Offset<AnimationFlatbuffer.RotatedRectFB> CreateRotatedRectFB(FlatBufferBuilder builder, short CenX, short CenY, short W, short H, short AngleDeg, ushort Color) {
    builder.Prep(2, 12);
    builder.PutUshort(Color);
    builder.PutShort(AngleDeg);
    builder.PutShort(H);
    builder.PutShort(W);
    builder.PutShort(CenY);
    builder.PutShort(CenX);
    return new Offset<AnimationFlatbuffer.RotatedRectFB>(builder.Offset);
  }
}

public struct CircleFB : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public CircleFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public short X0 { get { return __p.bb.GetShort(__p.bb_pos + 0); } }
  public short Y0 { get { return __p.bb.GetShort(__p.bb_pos + 2); } }
  public short R { get { return __p.bb.GetShort(__p.bb_pos + 4); } }
  public byte Quadrants { get { return __p.bb.Get(__p.bb_pos + 6); } }
  public short Delta { get { return __p.bb.GetShort(__p.bb_pos + 8); } }
  public ushort Color { get { return __p.bb.GetUshort(__p.bb_pos + 10); } }

  public static Offset<AnimationFlatbuffer.CircleFB> CreateCircleFB(FlatBufferBuilder builder, short X0, short Y0, short R, byte Quadrants, short Delta, ushort Color) {
    builder.Prep(2, 12);
    builder.PutUshort(Color);
    builder.PutShort(Delta);
    builder.Pad(1);
    builder.PutByte(Quadrants);
    builder.PutShort(R);
    builder.PutShort(Y0);
    builder.PutShort(X0);
    return new Offset<AnimationFlatbuffer.CircleFB>(builder.Offset);
  }
}

public struct AnimationFrameFB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static AnimationFrameFB GetRootAsAnimationFrameFB(ByteBuffer _bb) { return GetRootAsAnimationFrameFB(_bb, new AnimationFrameFB()); }
  public static AnimationFrameFB GetRootAsAnimationFrameFB(ByteBuffer _bb, AnimationFrameFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AnimationFrameFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Duration { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public ushort FillColor { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public AnimationFlatbuffer.PrimitiveFB PrimitivesType(int j) { int o = __p.__offset(8); return o != 0 ? (AnimationFlatbuffer.PrimitiveFB)__p.bb.Get(__p.__vector(o) + j * 1) : (AnimationFlatbuffer.PrimitiveFB)0; }
  public int PrimitivesTypeLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<AnimationFlatbuffer.PrimitiveFB> GetPrimitivesTypeBytes() { return __p.__vector_as_span<AnimationFlatbuffer.PrimitiveFB>(8, 1); }
#else
  public ArraySegment<byte>? GetPrimitivesTypeBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public AnimationFlatbuffer.PrimitiveFB[] GetPrimitivesTypeArray() { int o = __p.__offset(8); if (o == 0) return null; int p = __p.__vector(o); int l = __p.__vector_len(o); AnimationFlatbuffer.PrimitiveFB[] a = new AnimationFlatbuffer.PrimitiveFB[l]; for (int i = 0; i < l; i++) { a[i] = (AnimationFlatbuffer.PrimitiveFB)__p.bb.Get(p + i * 1); } return a; }
  public TTable? Primitives<TTable>(int j) where TTable : struct, IFlatbufferObject { int o = __p.__offset(10); return o != 0 ? (TTable?)__p.__union<TTable>(__p.__vector(o) + j * 4) : null; }
  public int PrimitivesLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<AnimationFlatbuffer.AnimationFrameFB> CreateAnimationFrameFB(FlatBufferBuilder builder,
      uint duration = 0,
      ushort fillColor = 0,
      VectorOffset primitives_typeOffset = default(VectorOffset),
      VectorOffset primitivesOffset = default(VectorOffset)) {
    builder.StartTable(4);
    AnimationFrameFB.AddPrimitives(builder, primitivesOffset);
    AnimationFrameFB.AddPrimitivesType(builder, primitives_typeOffset);
    AnimationFrameFB.AddDuration(builder, duration);
    AnimationFrameFB.AddFillColor(builder, fillColor);
    return AnimationFrameFB.EndAnimationFrameFB(builder);
  }

  public static void StartAnimationFrameFB(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddDuration(FlatBufferBuilder builder, uint duration) { builder.AddUint(0, duration, 0); }
  public static void AddFillColor(FlatBufferBuilder builder, ushort fillColor) { builder.AddUshort(1, fillColor, 0); }
  public static void AddPrimitivesType(FlatBufferBuilder builder, VectorOffset primitivesTypeOffset) { builder.AddOffset(2, primitivesTypeOffset.Value, 0); }
  public static VectorOffset CreatePrimitivesTypeVector(FlatBufferBuilder builder, AnimationFlatbuffer.PrimitiveFB[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte((byte)data[i]); return builder.EndVector(); }
  public static VectorOffset CreatePrimitivesTypeVectorBlock(FlatBufferBuilder builder, AnimationFlatbuffer.PrimitiveFB[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePrimitivesTypeVectorBlock(FlatBufferBuilder builder, ArraySegment<AnimationFlatbuffer.PrimitiveFB> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePrimitivesTypeVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<AnimationFlatbuffer.PrimitiveFB>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartPrimitivesTypeVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static void AddPrimitives(FlatBufferBuilder builder, VectorOffset primitivesOffset) { builder.AddOffset(3, primitivesOffset.Value, 0); }
  public static VectorOffset CreatePrimitivesVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i]); return builder.EndVector(); }
  public static VectorOffset CreatePrimitivesVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePrimitivesVectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePrimitivesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartPrimitivesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<AnimationFlatbuffer.AnimationFrameFB> EndAnimationFrameFB(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<AnimationFlatbuffer.AnimationFrameFB>(o);
  }
}


static public class AnimationFrameFBVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Duration*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*FillColor*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyVectorOfData(tablePos, 8 /*PrimitivesType*/, 1 /*AnimationFlatbuffer.PrimitiveFB*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct AnimationFB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static AnimationFB GetRootAsAnimationFB(ByteBuffer _bb) { return GetRootAsAnimationFB(_bb, new AnimationFB()); }
  public static AnimationFB GetRootAsAnimationFB(ByteBuffer _bb, AnimationFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyAnimationFB(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, AnimationFBVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AnimationFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool InterruptCurrent { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public short AnimationCenterX { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)0; } }
  public short AnimationCenterY { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)0; } }
  public AnimationFlatbuffer.AnimationFrameFB? AnimationFrames(int j) { int o = __p.__offset(10); return o != 0 ? (AnimationFlatbuffer.AnimationFrameFB?)(new AnimationFlatbuffer.AnimationFrameFB()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int AnimationFramesLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<AnimationFlatbuffer.AnimationFB> CreateAnimationFB(FlatBufferBuilder builder,
      bool interruptCurrent = false,
      short animationCenterX = 0,
      short animationCenterY = 0,
      VectorOffset animationFramesOffset = default(VectorOffset)) {
    builder.StartTable(4);
    AnimationFB.AddAnimationFrames(builder, animationFramesOffset);
    AnimationFB.AddAnimationCenterY(builder, animationCenterY);
    AnimationFB.AddAnimationCenterX(builder, animationCenterX);
    AnimationFB.AddInterruptCurrent(builder, interruptCurrent);
    return AnimationFB.EndAnimationFB(builder);
  }

  public static void StartAnimationFB(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddInterruptCurrent(FlatBufferBuilder builder, bool interruptCurrent) { builder.AddBool(0, interruptCurrent, false); }
  public static void AddAnimationCenterX(FlatBufferBuilder builder, short animationCenterX) { builder.AddShort(1, animationCenterX, 0); }
  public static void AddAnimationCenterY(FlatBufferBuilder builder, short animationCenterY) { builder.AddShort(2, animationCenterY, 0); }
  public static void AddAnimationFrames(FlatBufferBuilder builder, VectorOffset animationFramesOffset) { builder.AddOffset(3, animationFramesOffset.Value, 0); }
  public static VectorOffset CreateAnimationFramesVector(FlatBufferBuilder builder, Offset<AnimationFlatbuffer.AnimationFrameFB>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateAnimationFramesVectorBlock(FlatBufferBuilder builder, Offset<AnimationFlatbuffer.AnimationFrameFB>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateAnimationFramesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<AnimationFlatbuffer.AnimationFrameFB>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateAnimationFramesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<AnimationFlatbuffer.AnimationFrameFB>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartAnimationFramesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<AnimationFlatbuffer.AnimationFB> EndAnimationFB(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<AnimationFlatbuffer.AnimationFB>(o);
  }
  public static void FinishAnimationFBBuffer(FlatBufferBuilder builder, Offset<AnimationFlatbuffer.AnimationFB> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedAnimationFBBuffer(FlatBufferBuilder builder, Offset<AnimationFlatbuffer.AnimationFB> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class AnimationFBVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*InterruptCurrent*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*AnimationCenterX*/, 2 /*short*/, 2, false)
      && verifier.VerifyField(tablePos, 8 /*AnimationCenterY*/, 2 /*short*/, 2, false)
      && verifier.VerifyVectorOfTables(tablePos, 10 /*AnimationFrames*/, AnimationFlatbuffer.AnimationFrameFBVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
