namespace AnimationFlatbuffer;

struct LineFB {
	x0: int16;
	y0: int16;
	x1: int16;
	y1: int16;
	color: uint16;
}

struct TriangleFB {
    x0: int16;
    y0: int16;
    x1: int16;
    y1: int16;
    x2: int16;
    y2: int16;
    color: uint16;
}

struct RoundRectFB {
    x0: int16;
    y0: int16;
    w: int16;
    h: int16;
    radius: int16;
    color: uint16;
}

struct RotatedRectFB {
    cen_x: int16;
    cen_y: int16;
    w: int16;
    h: int16;
    angle_deg: int16;
    color: uint16;
}

struct CircleFB {
    x0: int16;
    y0: int16;
    r: int16;
    quadrants: ubyte;
    delta: int16;
    color: uint16;
}

union PrimitiveFB {LineFB, TriangleFB, RoundRectFB, RotatedRectFB, CircleFB}

table AnimationFrameFB {
	center_x: int16;
	center_y: int16;
	duration: uint32;
	fill_color: uint16;
	primitives: [PrimitiveFB];
}

table AnimationFB {
	center_x: int16;
	center_y: int16;
	frames: [AnimationFrameFB];
}

root_type AnimationFB;